name: Bug Report
description: DexterDB behaves incorrectly
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: dexter_version
    attributes:
      label: DexterDB version
      placeholder: e.g. 0.1.4
    validations:
      required: true

  - type: input
    id: node_version
    attributes:
      label: Node.js version
      placeholder: e.g. 18.19.0
    validations:
      required: true

  - type: input
    id: mongoose_version
    attributes:
      label: Mongoose version
      placeholder: e.g. 8.1.2
    validations:
      required: true

  - type: dropdown
    id: usage
    attributes:
      label: How are you using DexterDB?
      options:
        - CLI
        - Programmatic API
        - Both
    validations:
      required: true

  - type: textarea
    id: schema
    attributes:
      label: Schema definition
      description: Paste the relevant Mongoose schema(s).
      render: typescript
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Minimal steps or code snippet.
      render: typescript
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error output
      render: shell
