name: Feature Request
description: Suggest a new capability
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is impossible or painful today?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the API or CLI behavior.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example usage
      description: Show how a user would use this.
      render: typescript
